Add page for chain versions #208
provenance-io/explorer-frontend pull request #210
Opened 2021-12-22 16:33 UTC by jarrydallison

## Description

This PR adds "Stats" to the Nav Menu to allow users to view Provenance version history. It creates the redux actions/hooks/reducers for Stats, and updates multiple products to support a new table view and dropdown menu.

closes: #208

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [X] Targeted PR against correct branch
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

2022-01-04 20:27 UTC, webbushka requested changes

2022-01-04 20:27 UTC, webbushka commented on src/Components/Navigation/Components/NavMini.js
> +          style={style}
No inline styles, use styled-components instead

2022-01-04 20:27 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +const subMenuDrop = { padding: '3px 0 3px 7px', ...subMenuTop };
move these styles into the styled component with a prop instead

2022-01-04 20:27 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +  const buildLink = (linkName, { url, title, subMenu = {} }, style) => {
remove inline styles

2022-01-04 20:27 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +          style={isSubMenu ? subMenuTop : style}
remove inline styles and use a prop on the styled component instead

2022-01-04 20:27 UTC, webbushka commented on src/Components/Table/Table.js
> +        style = {},
remove

2022-01-04 20:27 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +// import { findLastIndex } from 'cypress/types/lodash';
remove this line

2022-01-04 20:27 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +// import { setConstantValue } from 'typescript';
remove this line

2022-01-04 20:27 UTC, webbushka commented on src/consts/urls.js
> +export const TOKEN_STATS_URL = `${BASE_URL}/token/stats`;
are these for future stats?

2022-01-04 20:27 UTC, webbushka commented on src/redux/reducers/statsReducer.js
> +  //To-Do: Add more here once this is working
still todo?

2022-01-04 20:27 UTC, webbushka commented on src/redux/reducers/statsReducer.js
> +  GET_UPGRADE_INFO, // To-Do: Add more here once this is working
still todo?

2022-01-04 20:27 UTC, webbushka commented on src/utils/table/formatTableData.js
> +            style: dataObj.skipped ? { textDecoration: 'line-through', fontStyle: 'italic' } : {},
use a bool instead and do the styles in the styled component with a prop

2022-01-05 00:18 UTC, jarrydallison commented on src/consts/urls.js
> +export const TOKEN_STATS_URL = `${BASE_URL}/token/stats`;
Yes that was the intent.

2022-01-05 00:19 UTC, jarrydallison commented on src/redux/reducers/statsReducer.js
> +  GET_UPGRADE_INFO, // To-Do: Add more here once this is working
nope, removed.

2022-01-05 00:19 UTC, jarrydallison commented on src/redux/reducers/statsReducer.js
> +  //To-Do: Add more here once this is working
nope, removed.

2022-01-05 00:20 UTC, jarrydallison commented on src/utils/table/formatTableData.js
> +            style: dataObj.skipped ? { textDecoration: 'line-through', fontStyle: 'italic' } : {},
done

2022-01-05 00:20 UTC, jarrydallison commented on src/Components/Table/Table.js
> +        <TableData title={hover || value} key={displayName} style={style}>
done

2022-01-05 00:20 UTC, jarrydallison commented on src/Components/Navigation/Components/NavStandard.js
> +          style={isSubMenu ? subMenuTop : style}
done

2022-01-05 00:20 UTC, jarrydallison commented on src/Components/Navigation/Components/NavStandard.js
> +  const buildLink = (linkName, { url, title, subMenu = {} }, style) => {
done

2022-01-05 00:20 UTC, jarrydallison commented on src/Components/Navigation/Components/NavStandard.js
> +const subMenuDrop = { padding: '3px 0 3px 7px', ...subMenuTop };
done

2022-01-05 00:21 UTC, jarrydallison commented on src/Components/Navigation/Components/NavStandard.js
> +// import { findLastIndex } from 'cypress/types/lodash';
done

2022-01-05 00:21 UTC, jarrydallison commented on src/Components/Navigation/Components/NavStandard.js
> +// import { setConstantValue } from 'typescript';
done

2022-01-05 00:21 UTC, jarrydallison commented on src/Components/Navigation/Components/NavMini.js
> +          style={style}
done

2022-01-05 02:23 UTC, webbushka requested changes

2022-01-05 16:16 UTC, jarrydallison commented on src/Components/Navigation/Components/NavMini.js
> +      text-decoration: ${submenudrop ? '' : `underline solid ${theme.FONT_NAV} 2px`};
done

2022-01-05 16:18 UTC, jarrydallison commented on src/Components/Navigation/Components/NavMini.js
> +          show={linkName === showSubMenu ? true : false}
done

2022-01-05 16:24 UTC, jarrydallison commented on src/Components/Table/Table.js
> +  `}
fixed

2022-01-05 16:25 UTC, jarrydallison commented on src/utils/table/formatTableData.js
> +            skipped: dataObj.skipped ? true : false,
doh! Yes we can

2022-01-05 19:26 UTC, webbushka requested changes

2022-01-05 19:26 UTC, webbushka commented on src/Components/Navigation/Components/NavMini.js
> +            buildLink(subName, Links[linkName].subMenu[subName], 'true')
use Boolean instead of string for `true`

2022-01-05 19:26 UTC, webbushka commented on src/Components/Navigation/Components/NavMini.js
> +    const active = pathname === url ? 'true' : undefined;
I know this isn't yours, but while you're in here can you update this to be 
```
const active = pathname === url || undefined
```

2022-01-05 19:26 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +    const active = pathname === url ? 'true' : undefined;
same as above `pathname === url || undefined`

2022-01-05 19:26 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +    const isSubMenu = Links[linkName]?.subMenu ? 'true' : undefined;
change to:
```
const isSubMenu = Links[linkName]?.subMenu || undefined;
```

2022-01-05 19:26 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +                buildLink(subName, Links[linkName].subMenu[subName], 'true')
change `true` to Boolean not String

2022-01-05 19:26 UTC, webbushka commented on src/utils/table/formatTableData.js
> +            value: dataObj.skipped ? 'Skipped' : dataObj.scheduled ? 'Scheduled' : '',
:nice:

2022-01-05 20:04 UTC, webbushka commented on src/Components/Navigation/Components/NavMini.js
> +          active={active}
in order to do the above need to update this to be:
```
$active={active}
```
and styles will need update as well as the variable name will be prefixed with `$`

2022-01-05 20:05 UTC, webbushka commented on src/Components/Navigation/Components/NavStandard.js
> +          active={active}
same thing here, prefix with `$`

2022-01-06 00:46 UTC, webbushka approved these changes
👍🏼

2022-01-06 00:48 UTC, merged