Link Tx validators to validators not accounts
provenance-io/explorer-frontend pull request #222
Opened 2022-01-10 16:29 UTC by jarrydallison

## Description

Fixed Tx validator links in Tx messages to link to the validator's page, not accounts.

closes: #182 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [X] Targeted PR against correct branch
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

2022-01-10 18:25 UTC, webbushka requested changes

2022-01-10 18:25 UTC, webbushka commented on src/Pages/Tx/Components/TxMsgs.js
> +            link: key === 'validatorAddress' ? `/validator/${value}` : `/accounts/${value}`,
I think just move validatorAddress into it's own case and don't have it fall through.

2022-01-11 18:52 UTC, jarrydallison commented on src/Pages/Tx/Components/TxMsgs.js
> +            link: key === 'validatorAddress' ? `/validator/${value}` : `/accounts/${value}`,
Updated. Left it in it's current spot since prefix is now a variable set through the comparison of chaincode types and the value in the Tx Msg

2022-01-12 20:31 UTC, webbushka requested changes

2022-01-12 20:31 UTC, webbushka commented on src/Pages/Tx/Components/TxMsgs.js
> +    if (!prefixesExist) {
use `isEmpty` from utils instead

```
if (isEmpty(chaincodePrefixes)) {
```

2022-01-12 20:31 UTC, webbushka commented on src/Pages/Tx/Components/TxMsgs.js
> +      {txMsgsLoading && !infoExists && chaincodePrefixesLoading && <Loading />}
wonder if this should be an `||`? in case `txMsgs` or `chaincodePrefixes` finishes before the other... as that would stop showing the loader even if it's not ready to render the page..
```
{((txMsgsLoading && !infoExists) || chaincodePrefixesLoading) && <Loading />}
```

2022-01-12 20:33 UTC, webbushka commented on src/Pages/Tx/Components/TxMsgs.js
> +            .find(pre => pre.prefix === value.substring(0, pre.prefix.length))
:oof: what is this comparing?

2022-01-13 22:13 UTC, jarrydallison commented on src/Pages/Tx/Components/TxMsgs.js
> +      {txMsgsLoading && !infoExists && chaincodePrefixesLoading && <Loading />}
yeah I agree. Changed!

2022-01-13 23:14 UTC, jarrydallison commented on src/Pages/Tx/Components/TxMsgs.js
> +            .find(pre => pre.prefix === value.substring(0, pre.prefix.length))
made a function with regex, added some notes

2022-01-14 00:48 UTC, webbushka requested changes

2022-01-14 00:48 UTC, webbushka commented on src/Pages/Tx/Components/TxMsgs.js
> +  };
can refactor this to use find instead of foreach and you could chain the sort and find
```
const prefix = chaincodePrefixes
  .sort((a, b) => (a.prefix.length > b.prefix.length ? 1 : -1))
  .find((pre) => value.match(pre.prefix))
  ?.type?.toLowerCase();
return prefix === "account" ? `${prefix}s` : prefix;
```

2022-01-14 13:51 UTC, jarrydallison commented on src/Pages/Tx/Components/TxMsgs.js
> +  };
Completed.

2022-01-14 17:35 UTC, webbushka approved these changes

2022-01-14 17:35 UTC, merged