Jarryd/248/add validator icons
provenance-io/explorer-frontend pull request #253
Opened 2022-01-29 14:01 UTC by jarrydallison

## Description

This PR adds validator icons to validator tables.

closes: #248 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [X] Targeted PR against correct branch
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [X] Re-reviewed `Files changed` in the Github PR explorer

2022-01-31 18:44 UTC, minxylynx requested changes

2022-01-31 18:44 UTC, minxylynx commented on src/redux/reducers/accountsReducer.js
> +        accountRedelegations: payload.records.reverse(),
As redelegations and unbondings come in unordered, and in separate lists, I would add an order/list reverse to the combined list rather than to the initial responses.

2022-01-31 22:00 UTC, jarrydallison commented on src/redux/reducers/accountsReducer.js
> +        accountRedelegations: payload.records.reverse(),
corrected in the accountUnbondings component.

2022-02-01 20:56 UTC, minxylynx commented on src/Pages/Accounts/Components/AccountButtons/Components/AccountUnbondings.js
> +        .sort((a, b) => a.endTime.millis - b.endTime.millis)
nice

2022-02-01 20:57 UTC, minxylynx approved these changes
LGTM

2022-02-01 20:57 UTC, merged